// Fictional sample contacts for the Tend demo. Edit this list to change people and conversations.
window.TEND_DATA = {
  user: { name: "Jordan", year: "Junior", graduation: 2027 },
  event: { id: "fall-fair", name: "Fall Career Fair", date: "October 14" },
  contacts: [
    {id:"maria-lopez",name:"Maria Lopez",role:"Recruiter",company:"Northwind Consulting",met:"Fall Career Fair",event:"Fall Career Fair",date:"Oct 14",color:"#4f46e5",interests:["Colts football","Alumni network"],promises:["Apply by Nov 1","Flag the application"],summary:"Fellow alum who offered to flag Jordan’s application after it is submitted.",notes:["Offered to flag the application. Apply by November 1.","We both cheered for the Colts and compared favorite game-day snacks."],starred:true,pending:true},
    {id:"david-chen",name:"David Chen",role:"Analyst",company:"Brightline Health",met:"Fall Career Fair",event:"Fall Career Fair",date:"Oct 14",color:"#0f766e",interests:["Healthcare strategy","Reading"],promises:["Send book recommendation"],summary:"Shared a helpful book on healthcare strategy and offered to send the title.",notes:["Recommended a book on healthcare strategy after interning there two summers ago."],starred:true,pending:true},
    {id:"priya-shah",name:"Priya Shah",role:"Talent Lead",company:"Summit Financial",met:"Fall Career Fair",event:"Fall Career Fair",date:"Oct 14",color:"#b45309",interests:["Marathons","Summer analyst roles"],promises:["Share analyst application link"],summary:"Hiring for summer analyst roles and is happy to share the application link.",notes:["Runs marathons and suggested applying early for summer analyst roles."],starred:true,pending:true},
    {id:"alex-rivera",name:"Alex Rivera",role:"Product Manager",company:"Lumen Labs",met:"Fall Career Fair",event:"Fall Career Fair",date:"Oct 14",color:"#be4bdb",interests:["Startup podcasts"],promises:["Email about spring internship"],summary:"Talked about a startup podcast and invited Jordan to email about a spring internship.",notes:["Asked Jordan to follow up about the spring internship."],starred:false},
    {id:"sam-williams",name:"Sam Williams",role:"Design Recruiter",company:"Pinecone Creative",met:"Fall Career Fair",event:"Fall Career Fair",date:"Oct 14",color:"#c2415d",interests:["Accessible design","Running"],promises:["Send portfolio tips"],summary:"Shared practical portfolio advice and offered to send a short review checklist.",notes:["Met near the design showcase."]}
    ,{id:"olivia-martin",name:"Olivia Martin",role:"Campus Recruiter",company:"Redwood Systems",met:"Fall Career Fair",event:"Fall Career Fair",date:"Oct 14",color:"#2563eb",interests:["Women in tech","Board games"],promises:["Invite to alumni panel"],summary:"Offered to invite Jordan to the next alumni panel.",notes:["Recommended connecting with the local alumni group."]},
    {id:"ethan-brooks",name:"Ethan Brooks",role:"Operations Associate",company:"Harborstone Group",met:"Fall Career Fair",event:"Fall Career Fair",date:"Oct 14",color:"#15803d",interests:["Supply chains","Cooking"],promises:["Share operations role details"],summary:"Works in operations and offered to share what a typical week looks like.",notes:["Talked about how operations teams work across departments."]},
    {id:"grace-kim",name:"Grace Kim",role:"People Partner",company:"Juniper Works",met:"Fall Career Fair",event:"Fall Career Fair",date:"Oct 14",color:"#9333ea",interests:["Mentoring","Hiking"],promises:["Send early careers page"],summary:"Encouraged Jordan to explore the early careers program and offered a link.",notes:["Met at the career fair welcome table."]},
    {id:"prof-evans",name:"Professor Riley Evans",role:"Marketing Professor",company:"Westbridge University",met:"Marketing seminar",event:"Campus",date:"Sep 29",color:"#0f766e",interests:["Consumer research","Gardening"],promises:["Review project outline"],summary:"Will review Jordan’s consumer research project outline before the next seminar.",notes:["Suggested narrowing the audience in the project question."],starred:true},
    {id:"nina-patel",name:"Nina Patel",role:"Internship Manager",company:"Cedar Ridge Studio",met:"Summer internship",event:"Internship",date:"Aug 18",color:"#b45309",interests:["Brand strategy","Cycling"],promises:["Write reference letter"],summary:"Former manager who offered to be a reference for brand strategy roles.",notes:["Asked for an updated resume before writing a reference."],starred:true},
    {id:"marcus-green",name:"Marcus Green",role:"Alumni Panelist",company:"Stonepath Analytics",met:"Alumni panel",event:"Alumni Panel",date:"Sep 12",color:"#2563eb",interests:["Data storytelling","Basketball"],promises:["Share case interview tips"],summary:"Shared a data storytelling framework and offered case interview tips.",notes:["Connected after the business school alumni panel."]},
    {id:"aisha-johnson",name:"Aisha Johnson",role:"Community Organizer",company:"Maple Street Center",met:"Small group",event:"Community",date:"Sep 21",color:"#be4bdb",interests:["Volunteering","Faith"],promises:["Send volunteer schedule"],summary:"Coordinates a monthly neighborhood volunteer day.",notes:["Invited Jordan to help with the October food drive."]},
    {id:"noah-turner",name:"Noah Turner",role:"Research Assistant",company:"Westbridge University",met:"Research lab",event:"Campus",date:"Sep 8",color:"#c2415d",interests:["Behavioral science","Chess"],promises:["Share research paper"],summary:"Research teammate who found a paper relevant to Jordan’s class project.",notes:["Discussed a new study on decision making."]},
    {id:"ella-foster",name:"Ella Foster",role:"Program Coordinator",company:"Northside Fellows",met:"Leadership workshop",event:"Workshop",date:"Aug 30",color:"#15803d",interests:["Public service","Travel"],promises:["Introduce to fellowship alum"],summary:"Can connect Jordan with a recent fellow who works in public service.",notes:["Met during the campus leadership workshop."]}
  ],
  followups: ["maria-lopez","david-chen","priya-shah"],
  reminders: [
    {contact:"maria-lopez",when:"Friday",reason:"Application deadline is November 1",draft:"Hi Maria, I submitted my application to Northwind Consulting. Thanks again for offering to flag it. I appreciated hearing how you made the jump from campus to consulting, and I’m excited about the opportunity to learn more."},
    {contact:"prof-evans",when:"Tomorrow",reason:"Share the project outline before seminar",draft:"Hi Professor Evans, I’ve tightened the audience for my consumer research project. Would you have a chance to look over the outline before our next seminar? Your suggestion helped me make the question much more focused."},
    {contact:"david-chen",when:"This week",reason:"Ask for the healthcare strategy book",draft:"Hi David, I enjoyed our conversation at the career fair about your two summers at Brightline Health. You mentioned a book on healthcare strategy that helped you get started. Would you mind sending me the title when you have a moment? Thanks for the recommendation."}
  ],
  digest: [
    {contact:"nina-patel",reason:"You have been meaning to send Nina your updated resume.",draft:"Hi Nina, I’ve updated my resume with my latest project work. Thanks again for offering to be a reference. Would you be open to taking a quick look when you have a chance?"},
    {contact:"marcus-green",reason:"Marcus offered to share case interview tips.",draft:"Hi Marcus, I’ve been practicing case interviews and remembered your data storytelling framework from the alumni panel. If you have a few tips you could share, I’d really appreciate it."},
    {contact:"ella-foster",reason:"Ella offered to introduce you to a recent fellow.",draft:"Hi Ella, I wanted to follow up on your offer to introduce me to a recent Northside Fellow. I’d love to hear about their path into public service whenever it works for you."}
  ],
  events: [
    {name:"Fall Career Fair",date:"October 14",count:8,id:"fall-fair"},
    {name:"Marketing seminar",date:"September 29",count:1},
    {name:"Alumni panel",date:"September 12",count:1},
    {name:"Leadership workshop",date:"August 30",count:1},
    {name:"Summer internship",date:"August 18",count:1}
  ]
};
